# Generated by Django 5.1.3 on 2024-12-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogInRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
