# Generated by Django 5.1.3 on 2024-12-20 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogInRegistration', '0003_customeruser_imageurl_alter_customeruser_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(default='This is a default text')),
                ('imageUrl', models.CharField(default='images/userhold.png', max_length=1000)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='customer_likes', to='LogInRegistration.customeruser')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogInRegistration.customeruser')),
            ],
        ),
    ]
