# Generated by Django 5.1.3 on 2024-12-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogInRegistration', '0006_alter_post_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='default comment')),
                ('dateCreated', models.DateTimeField(auto_now=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogInRegistration.post')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogInRegistration.customeruser')),
            ],
        ),
    ]
